### PR TITLE
Single-Cell lab updates

### PR DESCRIPTION
**Pull request by neoformit**
@nomadscientist 
- Replace AU footer with embedded snippet
- Add interactive tools to the SC tool panel view

### CODE REVIEW

**Comment by neoformit** [comment]
@paulzierep

**Comment by neoformit** [comment]
Will need revision after #169 merges

**Comment by neoformit** [comment]
Have refactored to match the new structure @bebatut

**Comment by bebatut** [comment]
Thanks @neoformit

**Pull request merged**
