### PR TITLE
Format with black and lint with ruff and mypy

### PR DESCRIPTION
**Pull request by nsoranzo**
Add continuous integration for linting.

No functional changes. Open PRs would touching the Python script will need a rebase/merge.

### CODE REVIEW

**Comment by bebatut** [comment]
Argh. This PR and the one I am working on will be conflicting a lot 😅

**Comment by nsoranzo** [comment]
Sooooorrry

**Comment by bebatut** [comment]
What would be the best approach? Getting yours first or mine?

**Comment by nsoranzo** [comment]
Mine is going to conflict with all others, and it does some good code-style checks (mypy in particular), so I'd suggest mine first :blush:

**Comment by bebatut** [comment]
Ok. Let's do that then

**Comment by nsoranzo** [comment]
Thanks!

**Pull request merged**
