### PR TITLE
Final paper edits

### PR DESCRIPTION
**Pull request by supernord**
Final edits based on preview generated here: http://preview.biohackrxiv.org/papers/048b4ccc-375d-4fde-9a72-f127e5a25953/paper.pdf

### CODE REVIEW

**Review by matuskalas — CHANGES_REQUESTED** [review]
Awesome 🙌🏽🙌🏽 Giant thanks for debugging & fixing all this!!! 🙏🏽🙏🏽

One issue left is that some of the citations lack proper capitalisation in their titles (e.g. "galaxy") . Double curly brackets in all titles should fix that.

And a question: Should the ToolShed article be cited (also) as usesDataFrom? Or do we in fact not use any data from it, only from the repos with wrappers?

**Comment by supernord** [comment]
Thanks @matuskalas 
If you make those edits, I can create a final preview and then submit.

**Comment by supernord** [comment]
@paulzierep - what do you think about the toolshed reference?

**Comment by paulzierep** [comment]
> I'm doing the needed edits in the .bib, which will be a separate, non-conflicting PR. So this one can in my opinion be merged.
> 
> The only question I have left here, and it is not important (It's more my own curiosity): Should the ToolShed article be cited (also) as usesDataFrom? Or do we in fact not use any data from it, only from the repos with wrappers?

The Tool Metadata Extractor does not use the ToolShed at all. As an explanation: currently it is not really useful for us since we cannot get the metadata we want via the API, that's why we scrape the wrapper code directly. So I think the current reference is fine.

**Review by paulzierep — APPROVED** [review]
If it renders fine, it is good to go ! Thank you all for the help and support!

**Comment by bebatut** [comment]
Should we discuss the author's order?

**Pull request merged**
