### PR TITLE
Update author order for the preprint

### PR DESCRIPTION
**Pull request by bebatut**
As suggested in #86

### CODE REVIEW

**Comment by paulzierep** [comment]
Should we add the shared first authorship with asterisk or something, I know it's just a preprint, but still ...

**Comment by bebatut** [comment]
That would be good if you can find how to do it

**Comment by supernord** [comment]
Example here from one of the other BioHackathon projects
https://github.com/elixir-europe/biohackathon-projects-2023/blob/main/20/biohackrxiv/paper.md?plain=1#L129

**Comment by bebatut** [comment]
> Example here from one of the other BioHackathon projects
https://github.com/elixir-europe/biohackathon-projects-2023/blob/main/20/biohackrxiv/paper.md?plain=1#L129

Added something like this. Thanks @supernord

**Pull request merged**
